modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="gtu"
version="${version}"
displayName="GregTech Intergalactical"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="GregoriusTechneticies for his work on GregTech" #optional
authors="Muramasa"
description='''The approved continuation of GregTech 5 Unoficial'''
[[dependencies.gtu]]
    modId="antimatter"
    mandatory=true
    #versionRange="[${antimatter_version},)"
    versionRange="0.0.1"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gtu]]
    modId="forge"
    mandatory=true
    #versionRange="[${forge_version},)"
    versionRange="31.0.1"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtu]]
    modId="minecraft"
    mandatory=true
    #versionRange="[${minecraft_version}]"
    versionRange="1.15.2"
    ordering="NONE"
    side="BOTH"